<?php

/*
*********************************************************
Class: phpforumPlus 
Description: a php class for rapid forums creation
Author: Tsiavos Chris <jaames@freemail.gr>
Date: Sep 2003
*********************************************************
Requirements: PHP,RDBMS(MySQL or PostgreSQL),a JavaScript
enabled web browser
*********************************************************
User Methods
*********************************************************
*********************************************************
FOR EXAMPLES & USAGE READ THE ACCOMPANING README FILE
*********************************************************
phpforumplus::set_member($topic)
sets the registered member name for the discussion board
-------------------------------------------------------------------------------
phpforumplus::display()
displays all the threads related to the topic plus information about the thread's sender,date &
number of replies
-------------------------------------------------------------------------------
phpforumplus::display_thread()
displays the select thread message body plus all the replies related to the current thread
-------------------------------------------------------------------------------
phpforumplus::reply_to_thread()
use this function to reply to the selected thread
-------------------------------------------------------------------------------
phpforumplus::post_new_thread()
use this function to post a new thread to the selected topic
-------------------------------------------------------------------------------
phpforumplus::display_forums()
used to display the forum topics with short content descriptions 
*********************************************************
Internal Methods
*********************************************************
phpforumplus::connect_to_database()
function providing connection with the database hosting the forums
--------------------------------------------------------------------------------
phpforumplus::close_database()
disconnects from the database hosting the forums
---------------------------------------------------------------------------------
phpforumplus::init_variables()
used to initialize the $_GET & other variables utilized in several places within this script
---------------------------------------------------------------------------------
phpforumplus::validate($variable)
this function is used to validate $_GET variables used in different sections of the script for malicious entries.
Such variables include $_GET["forumid"],$_GET["msgid"] and others
---------------------------------------------------------------------------------
phpforumplus::display_error($error_number)
used to graphically display error messages generated by unsuccessfull $_GET validated variables
---------------------------------------------------------------------------------
phpforumplus::threads_per_page($msg_count)
used to calculate the number of thread pages  according to $theads_limit_per_page value  
---------------------------------------------------------------------------------
phpforumsplus::display_thread_body($hd)
used to display the body of the current thread
---------------------------------------------------------------------------------
phpforumplus::display_replies($hd)
used to display all replies associated with the current thread
---------------------------------------------------------------------------------
phpforumsplus::reply_post_table($action,$headline)
used to provide the html data needed by the reply_to_thread and post_new_thread functions
--------------------------------------------------------------------------------- 
phpforumplus::create_menu()
creates the menu buttons utilized in "post new thread" & "reply to thread" scripts providing a limited number of allowable
html tags for the body of a new or reply thread
---------------------------------------------------------------------------------
phpforumplus::insert_javascript($for_what)
inserts the javascript needed by the menu buttons to function properly
---------------------------------------------------------------------------------
phpforumplus::execute_query($query)
function that executes the sql query defined in the $query variable
--------------------------------------------------------------------------------- 
*/
//require_once("DB.php");<<<<<<<<<<<<<<<<<<<<<<<<<,,

class phpforumPlus {
/*//----------------environment options--------------
var $member;
//----------------end environment options---------
//----------------page options----------------------
var $display_forum;
var $view_thread_page;
var $reply_page;
var $post_new_thread_page;
//-----------------end_page options---------------
//---------------database options------------------
var $threads_limit_per_page;
var $thread_length_limit;
var $reply_length_limit;
var $headline_length_limit;
var $database_type;
var $db_host;
var $db_user;
var $db_passwd;
var $forum_database;
var $topic_tables;
var $table_struct;
//-------------end_database options------------
//-------------table options-----------------------
var $table_width;
var $table_height;
var $table_cell_spacing;
var $table_cell_padding;
var $table_border;
var $forum_icon;
var $thread_icon;
var $hot_thread_icon;
var $hot_thread_limit;
//------------end_table options------------------
//------------stylesheet options------------------
var $style_name;
var $table_info_section;
var $table_body_section;
var $table_footer_section;
//-------------end-stylesheet-options-----------	
//------------site options-------------------------
var $welcome_msg;
var $site_administrator;
//-------------end_site options------------------*/
//------------internal vatiables-------------------
var $hd;
var $int_forumid;
var $int_post_table;
var $int_replies_table;
var $int_sort_by;
var $int_order;
var $int_position;
var $int_id;
var $int_target;
var $int_body;
var $int_member;
var $int_headline;
var $int_date_posted;
var $int_post_views;
var $int_post_headline;
var $int_post_body;
var $int_post_date_posted;
var $int_post_member;
//------------end internal variables-------------


  function init_variables() {
     //$this->int_target=seturl('t='.getReq('t'));//"/action.func?t=".getreq('t');//seturl('t='.getReq('t'));//$_SERVER["PHP_SELF"];<<<<<<<<<<<<<<<<<<

     $this->int_forumid=$this->validate(getreq("forumid"));//$_GET["forumid"]);
     $this->int_sort_by=$this->validate(getreq("sort_by"));//$_GET["sort_by"]);
     $this->int_order=$this->validate(getreq("order"));//$_GET["order"]);
     $this->int_position=$this->validate(getreq("position"));//$_GET["position"]);

     $this->int_post_table=$this->topic_tables[$this->int_forumid][0];
     $this->int_replies_table=$this->topic_tables[$this->int_forumid][1];

     $this->int_id=$this->table_struct["table_replies"][0];
	 $this->int_member=$this->table_struct["table_replies"][1];
	 $this->int_headline=$this->table_struct["table_replies"][2];
	 $this->int_body=$this->table_struct["table_replies"][3];
     $this->int_date_posted=$this->table_struct["table_replies"][4];

     $this->int_post_member=$this->table_struct["table_posts"][1];
     $this->int_post_headline=$this->table_struct["table_posts"][2];
     $this->int_post_body=$this->table_struct["table_posts"][3];
     $this->int_post_date_posted=$this->table_struct["table_posts"][4];
     $this->int_post_views=$this->table_struct["table_posts"][5];
  }

  function set_member($mymember) {
  
     $this->member=$mymember;	
  }

  function validate($variable) {
     $db = GetGlobal('db');

     if (!isset($variable)) $this->display_error("Missing GET arguments in URL");

     switch ($variable) {
	
           case (GetReq("forumid"))://($_GET["forumid"]):
                   foreach ($this->topic_tables as $topic => $key) {
		             $topic=urlencode($topic);
                   	 if (md5($topic)==md5(urlencode($variable))) return ($variable);
                   }
                   $this->display_error("Invalid forum selected");
                                                                  
           case (GetReq("msgid"))://($_GET["msgid"]):    
		           $fid = getreq('forumid');//_GET["forumid"]
				   
                   //$resultset=$this->execute_query("select max(".$this->table_struct["table_posts"][0].") from ".$this->topic_tables[$fid][0]);
				   $sSQL = "select max(".$this->table_struct["table_posts"][0].") from ".$this->topic_tables[$fid][0];
				   $resultset = $db->Execute($sSQL,2);
				   
                   //$msg_count=$resultset->fields[0];//fetchRow();
				   $msg_count = $db->fetch_array($resultset);
				   
                   if ($variable>$msg_count[0] || !ereg("^[0-9]+$",$variable))
                       $this->display_error("Invalid thread number");  
                   else 
                   return ($variable);   
                            
           case (GetReq("position"))://($_GET["position"]):
		           $t = getReq('t');
           	       //if (basename($_SERVER["PHP_SELF"])==$this->post_new_thread_page) {//???????<<<<<<<<
				   if ($t=='postfthread') {
           	        	return 0;
           	        	break;
           	       }
				   
				   $fid = GetReq('forumid');//_GET["forumid"]
				   
                   //$resultset=$this->execute_query("select max(".$this->table_struct["table_posts"][0].") from ".$this->topic_tables[$fid][0]);
				   $sSQL = "select max(".$this->table_struct["table_posts"][0].") from ".$this->topic_tables[$fid][0];
				   $resultset = $db->Execute($sSQL,2);
                   //msg_count=$resultset->fields[0];//fetchRow();
				   $msg_count = $db->fetch_array($resultset);
				   
                   if (empty($msg_count[0])) $this->display_error("Forum empty");
                   if ($variable>$msg_count[0]-1 || !ereg("^[0-9]+$",$variable))
                       $this->display_error("Invalid position identifier");  
                   else  
                       return ($variable);    
                       
           case (GetReq("sort_by"))://($_GET["sort_by"]):
	               $date_posted_field=$this->table_struct["table_posts"][4];
		           $member_field=$this->table_struct["table_posts"][1];
	               !preg_match("/^($date_posted_field|$member_field)$/",$variable) && $this->display_error("Invalid sort identifier");
                   return ($variable);
                      
           case (GetReq("order"))://($_GET["order"]):
           	       !preg_match("/^(asc|desc)$/",$variable) && $this->display_error("Invalid order value");       
                   return ($variable);
             
           case (GetParam("reply_body"))://($_POST["reply_body"]):
	               if (strlen($variable)>$this->reply_length_limit)
                     $this->display_error("Message too long");
                   else {
				     $variable2 = $this->replace_code_chars($variable); 
                     return addslashes(strip_tags($variable2,"<a><b><i>"));
				   }	 
                   
           case (GetParam("post_body"))://($_POST["post_body"]):
                   if (strlen($variable)>$this->thread_length_limit)
                     $this->display_error("Message too long");
                   else {
	                 //return addslashes(strip_tags($variable,"<a><b><i>"));
					 $variable2 = $this->replace_code_chars($variable);
					 return addslashes(strip_tags($variable2,"<a><b><i>"));
				   }	 
                
     }
  }
  
  function replace_code_chars($code) {
  
     $ret1 = str_replace("{","[@".ord("{")."]",$code);
	 $ret2 = str_replace("}","[@".ord("}")."]",$ret1);
	 $ret3 = str_replace(":","[@".ord(":")."]",$ret2);
	 $ret4 = str_replace("'","[@".ord("'")."]",$ret3);
	 $ret5 = str_replace("\\","[@".ord("\\")."]",$ret4);
	 $ret = str_replace(";","[@".ord(";")."]",$ret5);
	 
	 
	 return ($ret);
  }
  
  function show_code_chars($code) {
  
     $ret1 = str_replace("[@".ord("{")."]","{",$code);
	 $ret2 = str_replace("[@".ord("}")."]","}",$ret1);
	 $ret3 = str_replace("[@".ord(":")."]",":",$ret2);
	 $ret4 = str_replace("[@".ord("'")."]","'",$ret3);
	 $ret5 = str_replace("[@".ord("\\")."]","\\",$ret4);	 
	 $ret = str_replace("[@".ord(";")."]",";",$ret5);
	 
	 
	 return ($ret);  
  }

  function display_error($error) {
  
     $inf="We are sorry for the inconvenience.If you see this message regularly contact the site administator at <a href=\"mailto:$this->site_administrator\">$this->site_administrator</a>";
	 
     switch ($error) {
       case "Invalid forum selected":
               $error_descr="The requested forum was not found.$inf";
               break;
       case "Invalid thread number":
               $error_descr="The requested thread was not found in database.$inf";
               break;
       case "Invalid position identifier":
               $error_descr="The requested forum portion cannot be displayed.$inf";
	           break;	
       case "Message too long":
               $error_descr="Your reply message was too long to be sent.Please try to reduce if possible your message length in order to be conformed to limits set by the site administrator";	
               $error_descr.=" <a href=\"mailto:$this->site_administrator\">$this->site_administrator</a>";
               break;
       case "Invalid sort identifier":
               $error_descr=$inf;
               break;
       case "Invalid order value":
               $error_descr=$inf;       
               break;
       case "Missing GET arguments in URL":
               $error_descr=$inf;
               break;
	   case localize("_MSGEMPTY"):		   
       case "Empty Subject or message body not permitted":
               $error_descr="Please type a valid subject or body for your message";
               break;
       case "Forum empty":
       	       $out .= "<strong>No threads have been uploaded for this forum topic.Be the first!</strong><br/>";
			   $out .= seturl("t=postfthread&forumid=".urlencode($this->int_forumid)."&position=0&sort_by=$this->int_sort_by&order=$this->int_order",'Post New Thread!');
       	       //$out .= "<a href=\"action.func?t=postfthread&forumid=".urlencode($this->int_forumid)."&position=0&sort_by=$this->int_sort_by&order=$this->int_order\">Post new thread</a>";
     }

	 $out = $this->message("Error!","<h2>".$error."<br>".$error_descr."</h2>");

     return ($out);
  }
		
  function message($title,$message) {
  
     $ewin = new window($title,$message);
	 $out = $ewin->render("center::50%::0::group_win_body::left::0::0::");
	 unset($ewin);
	 
	 return ($out);   
  }		

  function display_forums() {
	$db = GetGlobal('db');
	//$this->connect_to_database();
	
	$db_member=$this->table_struct["table_posts"][1];
	$db_headline=$this->table_struct["table_posts"][2];
	$db_date_posted=$this->table_struct["table_posts"][4];
	$db_id=$this->table_struct["table_posts"][0];
	
	
	foreach ($this->topic_tables as $topic=>$value) {
	
	            $sSQL = "select * from ".$this->topic_tables[$topic][0]." order by $db_date_posted desc";            
				$resultset = $db->Execute($sSQL,2);
				$row=$db->fetch_array($resultset);	            
				
	            $id[$topic]=$row[$db_id];
	            $member[$topic]=$row[$db_member];
	            $headline[$topic]=$row[$db_headline];
	            $date_posted[$topic]=$row[$db_date_posted];		
	            $msg_count[$topic]=$db->num_Rows($resultset);
	}
	
	foreach ($this->topic_tables as $topic => $key) {
	
	     if (!empty($this->forum_icon[$topic])) 
	        $forum_icon[$topic]= loadimagexy($this->forum_icon[$topic],40,40);
	     else {
	     	if ($has_forum_icon)
	          $forum_icon[$topic]="&nbsp;";
		 }	
	   
	     $link  = seturl("t=displayforum&forumid=".urlencode($topic)."&position=0&sort_by=$db_date_posted&order=desc",$topic);      		 
		 $link2 = seturl("t=showfthread&forumid=".urlencode($topic)."&msgid=".$id[$topic]."&position=0&sort_by=$db_date_posted&order=desc",$headline[$topic]);
		 
		 //last message to go	   
		 if ($msg_count[$topic])	   
		   $lastmessage = $member[$topic]."<br/>" . $link2 . "<br/>" . $date_posted[$topic];
		 	   
	     $topics[] = $forum_icon[$topic]. $link."<br/>".$key[2] . "||" .
					 $msg_count[$topic] . "||".
					 $lastmessage;
	}	 
    $mydbrowser = new browse($topics,null,null,null);	   
	$wout .= $mydbrowser->render('forums',0,$this); 
  	unset ($mydbrowser);	
	
    $out .= "<strong>$this->welcome_msg</strong>";	
	
    $ewin = new window(localize('_FORUMTOPICS',getlocal()),$wout);
	$out .= $ewin->render();
	unset($ewin);	   

    return ($out);
  }
  
  function selector() {
  
    $selfor = "<form name=\"jump\"><select name=\"jump_to_forum\" onChange=\"window.location=document.jump.jump_to_forum.options[document.jump.jump_to_forum.selectedIndex].value;\">" .
            "<option value=\"#\">".localize("_CHOOSE")." Forum</option>\n";

    foreach ($this->topic_tables as $forum=>$value) {
      $mlink = seturl("t=displayforum&forumid=".urlencode($forum)."&position=0&sort_by=".$this->table_struct["table_posts"][4]."&order=desc");
      //$link = "/action.func?"."t=displayforum&forumid=".urlencode($forum)."&position=0&sort_by=".$this->table_struct["table_posts"][4]."&order=desc";  
      $selfor .= "<option value=\"$mlink\">$forum - ".$value[2]."</option>\n";
    }
	
	$selfor .="</select></form>";
	
	return ($selfor);  
  }

  function display() {
    $db = GetGlobal('db'); 

	$this->init_variables();

	$sSQL = "select * from $this->int_post_table";
	$resultset = $db->Execute($sSQL,2);
    $msg_count=$db->num_Rows($resultset);
	
	$query = "select * from $this->int_post_table order by $this->int_sort_by $this->int_order limit $this->int_position,$this->threads_limit_per_page";
    $resultset = $db->Execute($query,2);

    $fixed_forumid=urlencode($this->int_forumid);
    !empty($this->forum_icon[$this->int_forumid]) && $forum_icon=loadimagexy($this->forum_icon[$this->int_forumid],40,40);		
		   
    while ($row = $db->fetch_array($resultset)) {	
	
	   !empty($this->thread_icon) && $has_icon=loadimagexy($this->thread_icon,18,18);
	   $msgid=$row[$this->table_struct["table_posts"][0]];
	
	   $replies_number="select count(*) as msg_count from $this->int_replies_table where $this->int_id=$msgid";
	   $replies_fetch = $db->Execute($replies_number,2); 
	   $replies_number_result = $db->fetch_array($replies_fetch);  		 
       $number_of_replies=$replies_number_result["msg_count"]; 
	   
       if ($number_of_replies>$this->hot_thread_limit) 
	     $has_icon = loadimagexy($this->hot_thread_icon,18,18);
	
       $member=$row[$this->int_post_member];
	   $headline=$row[$this->int_post_headline];
	   $date_posted=$row[$this->int_post_date_posted];
	   $views=$row[$this->int_post_views];

	   //isset($views) || $views=0;

	   $plink = seturl("t=showfthread&forumid=$fixed_forumid&msgid=$msgid&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order",$headline);
	   
	   $threads[] = $has_icon . $member . "||" .
	           $plink . "||" .
			   $date_posted . "||" .
			   $views . "||" .
			   $number_of_replies;
		

	    $current_msg_count++;
     }
	 
	 //image & info
    $link = seturl("t=postfthread&forumid=$fixed_forumid&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order",localize("_POST"));		 
	 $header[] = $forum_icon . $link;
	 $hattr[] = "left;30%";
     //sort form
	 $sort = $this->selector();
     $actioner = seturl('t='. GetReq('t') . "&forumid=" . urlencode($this->int_forumid)); 
     $sort .= "<form method=\"post\" action=\"$actioner\" type=\"multipart/form-data\">
<input type=\"hidden\" name=\"forumid\" value=\"$this->int_forumid\">
<input type=\"hidden\" name=\"position\" value=\"0\">";
     $sort .= $this->sortform(localize("_SORTTHREADSBY"),$this->int_sort_by,$this->int_order);	 
	 $header[] = $sort;
	 $hattr[] = "left;70%";
	 //header win
     $hwin = new window("",$header,$hattr);
	 $wout = $hwin->render("center::100%::0::group_article_selected::left::0::0::");
	 unset($hwin);		 
	 
	 
     $mydbrowser = new browse($threads,null,null,null);	   
	 $wout .= $mydbrowser->render('threads',0,$this); 
  	 unset ($mydbrowser);		
	 
	  	 
     //browsing
     $disp = $current_msg_count + $this->int_position;

	 $footer =  localize('_DISTHREADS',getlocal())." ".(int)($this->int_position+1)." ".localize('_TO'). $disp . " " . localize('_OF') . " " . $msg_count;
	 
	 $hr0_back = seturl('t='.getreq('t')."&forumid=".urlencode($this->int_forumid)."&position=".(int)($this->int_position-$this->threads_limit_per_page)."&sort_by=$this->int_sort_by&order=$this->int_order",localize('_BACK'));
	 $hr0_next = seturl('t='.getreq('t')."&forumid=".urlencode($this->int_forumid)."&position=$disp&sort_by=$this->int_sort_by&order=$this->int_order",localize('_NEXT'));
     $hr1_next = seturl('t='.getreq('t')."&forumid=".urlencode($this->int_forumid)."&position=$disp&sort_by=$this->int_sort_by&order=$this->int_order",localize('_NEXT'));
	 $hr1_back = seturl('t='.getreq('t')."&forumid=".urlencode($this->int_forumid)."&position=".(int)($this->int_position-$this->threads_limit_per_page)."&sort_by=$this->int_sort_by&order=$this->int_order",localize('_BACK'));
	 
     if ($this->int_position-1>0 && $this->int_position<$msg_count-$current_msg_count) {
       $footer .= "<br>" . $hr0_back .'|'. $hr0_next;
     }
     elseif ($this->int_position==0 && $msg_count>$current_msg_count)
       $footer .= "<br>" . $hr1_next;
	   
     if ($this->int_position==$msg_count-$current_msg_count && $this->int_position!=0) {
       $footer .= "<br>" . $hr1_back;
     }

     $footer .= "<br>" . $this->threads_per_page($msg_count);
	 
	 //footer win
     $fwin = new window("",$footer);
	 $wout .= $fwin->render("center::100%::0::group_article_selected::center::0::0::");
	 unset($fwin);	
	 
     $ewin = new window(localize('_THREADS',getlocal()),$wout);
	 $out .= $ewin->render();
	 unset($ewin);		  
 	  
     return ($out);
  }

  function threads_per_page($msg_count) {
  
     $out = localize('_GOTOPAGE',getlocal());//"Go to page: ";
     $page=1;
	 
     for ($i=0;$i<$msg_count;$i+=$this->threads_limit_per_page) {
	 
       if (getreq("position")==$i) {//($_GET["position"]==$i) 
	     $out .= seturl('t='.getreq('t')."&forumid=".urlencode($this->int_forumid)."&position=$i&sort_by=$this->int_sort_by&order=$this->int_order",
		         "<strong>$page</strong>");
	   }	 
       else {
         $out .= seturl('t='.getreq('t')."&forumid=".urlencode($this->int_forumid)."&position=$i&sort_by=$this->int_sort_by&order=$this->int_order",
		         $page);
	   }	 
		 
       $page++;
     }	

     return ($out);
  }

  function display_thread() {
  
     $out = $this->display_thread_body();
     $out .= $this->display_replies();
	 
     return ($out);
  }

  function display_thread_body() {
    $db = GetGlobal('db');
	
	$this->init_variables();
	
	!empty($this->style_name) && $has_stylesheet="<link rel=\"stylesheet\" href=\"$this->style_name\" type=\"text/css\">\n";	
	$msgid=$this->validate(GetReq("msgid"));//$_GET["msgid"]);
	$post_id=$this->table_struct["table_posts"][0];

    //CODE TO INC VIEWS!!!!!!
	$query0 = "select $this->int_post_views from $this->int_post_table where $post_id=$msgid";
	$res = $db->Execute($query0,2,1);		
	$incer = ($res[0]? $res[0]+1:1);	
	$query1 = "update $this->int_post_table set $this->int_post_views=$incer where $post_id=$msgid";  
	$db->Execute($query1,1);	  
    //echo $query1;

    //$link1 = seturl("t=replyfthread&forumid=".urlencode($this->int_forumid)."&msgid=$msgid&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order",'Reply');
	//$link2 = seturl("t=displayforum&forumid=".urlencode($this->int_forumid)."&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order",'Back');
	//$out .= "$link1 | $link2";
	
	$sSQL = "select count(*) as msg_count from $this->int_replies_table where $this->int_id=$msgid";
	$resultset = $db->Execute($sSQL,2);
	$replies_number_result = $db->fetch_array($resultset);
    $replies = $replies_number_result["msg_count"];	  

	$sSQL = "select * from $this->int_post_table where $post_id=$msgid";
	$resultset = $db->Execute($sSQL,2);
	$row = $db->fetch_array($resultset);
	$member=$row[$this->int_post_member];
	$date_posted=$row[$this->int_post_date_posted];
	$headline=stripslashes(trim($row[$this->int_post_headline]));
	$message_body=nl2br(trim(stripslashes($row[$this->int_post_body])));	
	
    $sSQL = "select count(*) as total_posts from $this->int_post_table where $this->int_post_member='$member'";	
	$resultset = $db->Execute($sSQL,2);
	$posts = $db->fetch_array($resultset);
	$posts_number=$posts["total_posts"];
	
	$threadbody[] = $member . "||" .
	                $posts_number . "||" .
			        $date_posted . "||" .
			        $headline . "||" .
			        $replies . "||" .
					$message_body;	
					
    $mydbrowser = new browse($threadbody,null,null,null);	   
	$wout = $mydbrowser->render('threadsbody',0,$this); 
  	unset ($mydbrowser);	
	 
    $ewin = new window(localize('_THREAD',getlocal()),$wout);
	$out .= $ewin->render();
	unset($ewin);						
	
    return ($out);
  }

  function display_replies() {
    $db = GetGlobal('db');

	$date_posted_column=$this->table_struct["table_replies"][4];
	$member_column=$this->table_struct["table_replies"][1];
    !empty($this->forum_icon[$this->int_forumid]) && $forum_icon=loadimagexy($this->forum_icon[$this->int_forumid],40,40);
	
	!empty($_POST["sort_by"]) || $_POST["sort_by"]="$date_posted_column";
	!empty($_POST["order"]) || $_POST["order"]="desc";
	$sort_by=$_POST["sort_by"];
	$order=$_POST["order"];
		
	$msgid = GetReq("msgid");//$_GET["msgid"];
	
	$sSQL = "select * from $this->int_replies_table where $this->int_id=$msgid order by $sort_by $order";
	$resultset = $db->Execute($sSQL,2);

	if ($db->num_Rows($resultset)>0) {

      $stylesheet_number=0;
      //while ($row=$resultset->fetchRow(DB_FETCHMODE_ASSOC)) {
	  while ($row = $db->fetch_array($resultset)) {

         $date_posted=$row[$this->int_date_posted];
         $headline=strip_tags(trim(stripslashes($row[$this->int_headline])));
         $member=$row[$this->int_member];
         $message_body=nl2br(trim(stripslashes($row[$this->int_body])));


         $replies[] = $member . "||" .
		              $headline . "||" .
					  $date_posted . "||" .
					  $message_body; 

      }
    }
	
	//image & info
    $link1 = seturl("t=replyfthread&forumid=".urlencode($this->int_forumid)."&msgid=$msgid&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order",localize('_REPLY',getlocal()));
	$link2 = seturl("t=displayforum&forumid=".urlencode($this->int_forumid)."&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order",localize('_BACK',getlocal()));
	$link = "$link1 | $link2";	
	$header[] = $forum_icon . $link;
	$hattr[] = "left;30%";	
	
	//sort form		
	$head = $this->selector();		
	$url=urlencode($this->int_forumid);
    $action = seturl('t='. GetReq('t') . "&forumid=$url&msgid=$msgid&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order");	
    $head .= "<form method=\"post\" action=\"$action\" type=\"multipart/form-data\">";
    $head .= $this->sortform(localize("_SORTREPLIESBY"),$sort_by,$order);
	$header[] = $head;
	$hattr[] = "left;70%";
	
	//header win
    $hwin = new window("",$header,$hattr);
	$wout = $hwin->render("center::100%::0::group_article_selected::left::0::0::");
	unset($hwin);			
	
    $mydbrowser = new browse($replies,null,null,null);	   
	$wout .= $mydbrowser->render('replies',0,$this); 
  	unset ($mydbrowser);	
	 
    $ewin = new window(localize('_REPLIES',getlocal()),$wout);
	$out .= $ewin->render();
	unset($ewin);	

    return ($out);
  }

  function reply_to_thread() {
    $db = GetGlobal('db');

	//$this->connect_to_database();
	$this->init_variables();

	$msgid=$this->validate(GetReq("msgid"));//$_GET["msgid"]);
	$post_id=$this->table_struct["table_posts"][0];

    $back = seturl("t=showfthread&forumid=".urlencode($this->int_forumid)."&msgid=$msgid&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order",localize("_BACK"));
	
    if (!empty($_POST["reply"])) {
	 
	
	    $message_body=$this->validate($_POST["reply_body"]);
	    $message_headline=addslashes(strip_tags($_POST["reply_headline"]));	
	    if (empty($message_headline) || empty($message_body)) {
		  $out .= $this->display_error(localize("_MSGEMPTY").$back);
		}  
        else {
          $date = get_datetime();//now();      
          $sSQL = "insert into $this->int_replies_table ($this->int_id,$this->int_member,$this->int_headline,$this->int_body,$this->int_date_posted) values ($msgid,'$this->member','$message_headline','$message_body','$date')";
          //echo $sSQL;		 
		  $res = $db->Execute($sSQL,2);
		
	      $out .= $this->message(localize("_REPLY"),"<h3>".localize("_MSGSEND")."</h3>".$back);
		}
		
    } 
    else {
        $sSQL = "select $this->int_post_headline from $this->int_post_table where $post_id=$msgid";
		$resultset = $db->Execute($sSQL,2);		
		$headline = $db->fetch_array($resultset);
		
	    $action = seturl('t='.GetReq('t')."&forumid=".urlencode($this->int_forumid)."&msgid=$msgid&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order");		
        $out .= $this->reply_post_table("reply","Re:".$headline[0],localize("_POST")." : ".$headline[0],$action,localize("_REPLY"));
    }

    return ($out);
  }

  function post_new_thread() {
    $db = GetGlobal('db');

	$this->init_variables();

    if (!empty($_POST["post"])) {
	  $message_body=$this->validate($_POST["post_body"]);
	  $message_headline=addslashes(strip_tags($_POST["post_headline"]));
	  if (empty($message_headline) || empty($message_body)) {
	    $out .= $this->display_error(localize("_MSGEMPTY"));
      }
	  else {
	    $date = get_datetime();//now();!!!	
        $insert_query="insert into $this->int_post_table ($this->int_post_member,$this->int_post_headline,$this->int_post_body,$this->int_post_date_posted) values ('$this->member','$message_headline','$message_body','$date')";
        //echo $insert_query;
	    $db->Execute($insert_query,2);
	   
	    $out .= $this->message(localize("_THREAD"),"<h3>".localize("_MSGSEND")."</h3>");
	  }	
	  $out .= seturl("t=displayforum&forumid=".urlencode($this->int_forumid)."&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order","Go Back!");
	}
    else {
	  $link = seturl("t=displayforum&forumid=".urlencode($this->int_forumid)."&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order","Go Back!")."<br/><br/>";
      $action = seturl("t=".getreq('t')."&forumid=".urlencode($this->int_forumid)."&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order");
	  
      //$out .= "<h4>Post new thread to $this->int_forumid Forum</h4>$link<br/><br/>";
	  //$out .= "<form name=\"post_form\" method=\"post\" action=\"$action\" type=\"multipart/form-data\">"; 
	  
      $out .= $this->reply_post_table("post","",localize("_THREAD").": $this->int_forumid Forum $link",$action,localize("_POST"));
 
    }

    return ($out);	
  }

  function reply_post_table($action,$headline,$title,$urlaction,$label=null) {
  
    if ($label) $postlabel = $label;
	       else $postlabel = $action;
	
	$date = date("D d M Y");
	$headline_name= $action . "_headline";
	$form_name = $action . '_form';
	$body_name = $action . "_body";	

	$menu = $this->create_menu();

    $wout = "<form name=\"$form_name\" method=\"post\" action=\"$urlaction\" type=\"multipart/form-data\">\n";
		

    $one[] = localize("_SUBJECT").":";
	$one_attr[] = "left;20%";
	$one[] = "<input type=\"text\" name=\"$headline_name\" size=\"$this->headline_length_limit\" maxlength=\"$this->headline_length_limit\" value=\"$headline\">";
	$one_attr[] = "left;80%";	
	$win1 = new window('',$one,$one_attr);
	$wout .= $win1->render("center::100%::0::group_article_selected::left::0::0::");
	unset($win1);
	
    $two[] = localize("_DATEP").":";
	$two_attr[] = "left;20%";
	$two[] = $date;
	$two_attr[] = "left;80%";		
	$win2 = new window('',$two,$two_attr);
	$wout .= $win2->render("center::100%::0::group_article_selected::left::0::0::");
	unset($win2);	
	
    $three[] = "HTML Options:";
	$three_attr[] = "left;20%";
	$three[] = $menu;
	$three_attr[] = "left;80%";		
	$win3 = new window('',$three,$three_attr);
	$wout .= $win3->render("center::100%::0::group_article_selected::left::0::0::");
	unset($win3);
	
    $four[] = localize("_MESSAGE").":";
	$four_attr[] = "left;20%";
	$four[] = "<textarea name=\"$body_name\" cols=\"70\" rows=\"20\" wrap=\"physical\"></textarea>";
	$four_attr[] = "left;80%";	
	$win4 = new window('',$four,$four_attr);
	$wout .= $win4->render("center::100%::0::group_article::left::0::0::");
	unset($win4);	
	

	$five[] = "<input type=\"submit\" name=\"$action\" value=\"$postlabel\">";
	$five_attr[] = "center;100%";	
	$win5 = new window('',$five,$five_attr);
	$wout .= $win5->render("center::100%::0::group_article_selected::left::0::0::");
	unset($win5);	
	
	$wout .= "</form>";
	
    $ewin = new window($title,$wout);
	$out .= $ewin->render();//"center::80%::0::window::left::0::0::");
	unset($ewin);					

    return ($out);
  }
  
  function sortform($label,$sort_by,$order) {
  
     $date_posted_column = $this->table_struct["table_posts"][4];
     $member_column = $this->table_struct["table_posts"][1];  
  
     $ret = "
<table>	 
<td>$label</td>
<td>
<select name=\"sort_by\">
<option value=\"$date_posted_column\">".localize("_DATEP")."</option>
<option value=\"$member_column\">".localize("_MEMBER")."</option>
</select>
</td>
<td>
$order 
</td>
<td>
<select name=\"order\">
<option value=\"asc\">".localize("_ASCE")."</option>
<option value=\"desc\">".localize("_DESC")."</option>
</select>
</td>
<td><input type=\"submit\" name=\"sort\" value=\"".localize("_SORT")."\"></td>
</tr>
<tr>
<td colspan=\"5\"><small><strong>".localize("_SORT").":</strong>$sort_by/$order</small></td>
</tr>
<tr>
</tr>
</table>
</form>
";  

    $win = new window('',$ret);
	$out = $win->render();
    unset($win);
	
    return ($out);

  }  

  function create_menu() {
  
    $menu= <<< CREATE_MENU
<input type="button"	name="strong" value="Bold" onclick="insert_element('bold');">
<input type="button"	name="em" value="Italics" onclick="insert_element('italics');">
<input type="button"	name="url" value="URL" onclick="insert_element('url');">
<input type="button"	name="Mail" value="Mail" onclick="insert_element('mail');">
CREATE_MENU;
    return $menu;
  }

  function insert_javascript($for_what) {
	
	if ($for_what=="for_post_page") {
	    $form_name="post_form";
	    $form_body="post_body";
	} 
	else {
	    $form_name="reply_form";
	    $form_body="reply_body";
	}
	
    //<script language="Javascript">
    //<!--	
    $out = <<< JAVASCRIPT_FOR_MENU
function insert_element(myelement) {
switch (myelement) {
case "bold" :
	var bold_text=window.prompt("Type the text you want to make bold ","");
	document.$form_name.$form_body.value=document.$form_name.$form_body.value+bold_text.bold();
	break;
case "italics" :
	var it_text=window.prompt("Type the text you want to make italics","");
	document.$form_name.$form_body.value=document.$form_name.$form_body.value+it_text.italics();
	break;
case "url" :
	var url_text=window.prompt("Type the url address you want to insert (without the http prefix)","");
	document.$form_name.$form_body.value=document.$form_name.$form_body.value+url_text.link("http://"+url_text);
	break;	
case "mail" :
	var mail=window.prompt("Type the e-mail address you want to insert ","");
	document.$form_name.$form_body.value=document.$form_name.$form_body.value+mail.link("mailto:"+mail);
	break;
}

}
JAVASCRIPT_FOR_MENU;
//-->
//</script>\n

    return ($out);
  }
  
  
  
	function browse($packdata,$view='') {
	  
	   $data = explode("||",$packdata);
	   
	   switch ($view) {
	       case 'forums' : $out = $this->viewforums($data[0],$data[1],$data[2]);
		                   break;
	       case 'threads': $out = $this->viewthreads($data[0],$data[1],$data[2],$data[3],$data[4]);
		                   break;	   
	       case 'threadsbody': $out = $this->viewthreadsbody($data[0],$data[1],$data[2],$data[3],$data[4],$data[5]);
		                   break;						   
	       case 'replies': $out = $this->viewreplies($data[0],$data[1],$data[2],$data[3]);
		                   break;							   
	   }	   
	   
	   return ($out);
	}  
  
    function viewforums($id,$total,$last) {

	   $data[] = $id;
	   $attr[] = "left;50%";
	   
	   $data[] = ($total?$total:'none');
	   $attr[] = "left;25%;";
	   
	   $data[] = ($last?$last:'none');
	   $attr[] = "left;25%;";				  	   

	    
	   $myarticle = new window('',$data,$attr);
	   $out = $myarticle->render("center::100%::0::group_article_high::left::0::0::"). "<hr>";
	   unset ($data);
	   unset ($attr);

	   return ($out);
    }	  
	
    function viewthreads($member,$headline,$date,$numviews,$numreplies) {

	   $data[] = ($member?$member:localize("_UNKNOWN"));
	   $attr[] = "left;20%";
	   
       $fixed_forumid=urlencode($this->int_forumid);
	   $link = seturl("t=showfthread&forumid=$fixed_forumid&msgid=$id&position=$this->int_position&sort_by=$this->int_sort_by&order=$this->int_order",$headline);
	   
	   $data[] = ($headline?$link:localize("_NOSUBJECT"));
	   $attr[] = "left;40%;";
	   
	   $data[] = ($date?$date:localize("_UNKNOWN")."&nbsp;");
	   $attr[] = "left;20%;";				  	   
	   
	   $data[] = ($numviews?$numviews:localize("_NONE")."&nbsp;");
	   $attr[] = "left;10%;";
	   
	   $data[] = ($numreplies ? $numreplies : localize("_NONE")."&nbsp;");
	   $attr[] = "left;10%;";		
	    
	   $mythread = new window('',$data,$attr);
	   $out = $mythread->render("center::100%::0::group_article_high::left::0::0::"). "<hr>";
	   unset ($data);
	   unset ($attr);
	   unset ($mythread);

	   return ($out);
    }	
  
    function viewthreadsbody($member,$posts_number,$date,$headline,$replies,$body) {

	   $data[] = ($member?$member:localize("_UNKNOWN"));
	   $attr[] = "left;10%";
	    
	   $data[] = ($posts_number?$posts_number:localize("_NONE")."&nbsp;");
	   $attr[] = "left;5%;";	   
	   
	   $data[] = ($date?$date:localize("_UNKNOWN")."&nbsp;");
	   $attr[] = "left;20%;";				  	   
	   
	   $data[] = ($headline?$headline:localize("_NOSUBJECT"));
	   $attr[] = "left;60%;";	   
	   
	   $data[] = ($replies?$replies:localize("_NONE")."&nbsp;");
	   $attr[] = "left;5%;";		
	    
	   $mythread = new window('',$data,$attr);
	   $out = $mythread->render("center::100%::0::group_article_selected::left::0::0::"). "<hr>";
	   unset ($data);
	   unset ($attr);
	   unset ($mythread);

	   $data2[] = localize("_MESSAGE");
	   $attr2[] = "left;35%";
	   
	   $data2[] = $this->show_code_chars($body);
	   $attr2[] = "left;65%";	   
	   
	   $mybody = new window('',$data2,$attr2);
	   $out .= "<br/>" . $mybody->render("center::100%::0::group_article::left::0::0::");
	   unset ($mybody);	   
	   
	   return ($out);
    }	  
	
    function viewreplies($member,$headline,$date,$body) {
	
	   $data[] = ($member?$member:localize("_UNKNOWN"));
	   $attr[] = "left;20%";	
	   
	   $data[] = ($headline?$headline:localize("_NOSUBJECT"));
	   $attr[] = "left;60%;";	
	   
	   $data[] = ($date?$date:localize("_UNKNOWN")."&nbsp;");
	   $attr[] = "left;20%;";		      	   	

	   $myreply = new window("",$data,$attr);
	   $out .= $myreply->render("center::100%::0::group_article_selected::left::0::0::");
	   unset ($myreply);	
	   
	   $data2[] = localize("_MESSAGE");
	   $attr2[] = "left;20%";
	   
	   $data2[] = $this->show_code_chars($body);
	   $attr2[] = "left;80%";		   
	   
	   $mybody = new window('',$data2,$attr2);
	   $out .= "<br/>" . $mybody->render("center::100%::0::group_article::left::0::0::");
	   unset ($mybody);		      
	   
	   return ($out);
    }		
  
	function headtitle($view=null) {

	   switch ($view) {
		 case 'replies' :	
	               $data[] = localize('_MEMBER',getlocal());//"Member";
	               $attr[] = "left;20%;";
	   
	               $data[] = localize('_SUBJECT',getlocal());//"Subject";
	               $attr[] = "left;60%;";				  

	               $data[] = localize('_DATEP',getlocal());//"Date Posted";   
	               $attr[] = "left;20%;";			 			     					   
		           break;	     
		 case 'threadsbody' :
	               $data[] = localize('_MEMBER',getlocal());//"Member";
	               $attr[] = "left;10%;";
				   
	               $data[] = localize('_THREADS',getlocal());//"Threads";
	               $attr[] = "left;5%;";				   
	   
	               $data[] = localize('_DATEP',getlocal());//"Date Posted";
	               $attr[] = "left;20%;";				  

	               $data[] = localize('_SUBJECT',getlocal());//"Subject";   
	               $attr[] = "left;60%;";			 
	   
	               $data[] = localize('_REPLIES',getlocal());//"Replies";
	               $attr[] = "left;5%;";				  					   
		           break;		 
		 case 'threads' :
	               $data[] = localize('_MEMBER',getlocal());//"Member";
	               $attr[] = "left;20%;";
	   
	               $data[] = localize('_SUBJECT',getlocal());//"Subject";
	               $attr[] = "left;40%;";				  

	               $data[] = localize('_DATEP',getlocal());//"Date Posted";   
	               $attr[] = "left;20%;";			 
				   
	               $data[] = localize('_VIEWS',getlocal());//"Views";
	               $attr[] = "left;10%;";
	   
	               $data[] = localize('_REPLIES',getlocal());//"Replies";
	               $attr[] = "left;10%;";				  					   
		           break;
				   
	     case 'forums' :
	     default :
	               $data[] = "Forums";
	               $attr[] = "left;50%;";
	   
	               $data[] = localize('_TPOSTS');
	               $attr[] = "left;25%;";				  

	               $data[] = localize('_LPOST');
	               $attr[] = "left;25%;";		   
       }
	    
	   $myarticle = new window('',$data,$attr);
	   $out = $myarticle->render("center::100%::0::group_article_high::left::0::0::"). "<hr>";
	   unset ($data);
	   unset ($attr);

	   return ($out);	
	}  
	
}



/*
class myphpforum extends phpforumPlus {
//----------------environment options--------------
	var $member;
//----------------end environment options--------
//------------------page_options------------------
	//var $display_forum="displayforum.php";
	//var $view_thread_page="showmessage.php";
	//var $reply_page="reply.php";
	//var $post_new_thread_page="post.php";
//-----------------end_page options---------------
//---------------database options------------------
	var $threads_limit_per_page=42;
	var $thread_length_limit=1000;
	var $reply_length_limit=1000;
	var $headline_length_limit=20;
	//var $database_type="mysql";
	//var $db_host="yourdbhost";
	//var $db_user="yourdbuser";
	//var $db_passwd="yourdbpasswd";
	//var $forum_database="forums";
	var $topic_tables=array("PHP"=>array("forum_posts","forum_replies","General php forum.Here you can discuss about all-things php.Must be valid member to post new threads"));
	var $table_struct=array("table_posts"=>array("id","member","headline","body","date_posted","views"),
	                        "table_replies"=>array("id","member","headline","body","date_posted"));
//-------------end_database options------------------
//-------------table options-------------------------
	//var $table_width=720;
	//var $table_height="";
	//var $table_cell_spacing=1;
	//var $table_cell_padding=0;
	//var $table_border=0;
	var $forum_icon=array("PHP"=>"images/sample_php.gif");
	var $thread_icon="images/thread_icon.gif";
	var $hot_thread_icon="images/hot_thread_icon.gif";
	var $hot_thread_limit=10;
//------------end_table options---------------------	
//------------stylesheet options---------------------
	//var $style_name="yourcssfile.css";
	//var $table_info_section="table_info";
	//var $table_body_section=array("table_body","table_body2");
	//var $table_footer_section="table_footer";
//-------------end-stylesheet-options--------------	
//------------site options----------------------------
    var $welcome_msg = "Welcome to our community";
    var $site_administrator = "webmaster@sth.somewhere";
//------------end_site options----------------------- 

    function myphpforum() {
	
  	  $this->welcome_msg = paramload('FORUM','welcome');
	  $this->site_administrator = paramload('FORUM','admin');
	}
} */ 
?>
